# Generated by Django 6.1 on 2026-08-14 01:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
